### ISSUE TITLE
KindSignatures: it would be helpful to talk about kind inference through method signatures

### ISSUE THREAD

**Issue by MinimumViablePerson** [i-am-tom/haskell-exercises#17]
@i-am-tom I am going through the haskell exercises, and in the `KindSignatures` section I noticed that you explain how `class Something a` will have a kind of `*`, and you can change that by adding the `KindSignatures` pragma.

I think this is great, but I feel there’s a step in between that could be explained to avoid confusion. That is, GHC will correctly infer the type of a based on the method signatures provided, and most of the time you will provide method signatures, so you might not need to jump straight into KindSignatures for it.

```haskell
class Functor f where
  fmap :: (a -> b) -> f a -> f b

:k Functor
Functor :: (* -> *) -> Constraint


class Stuff a where
   lol :: a b c d

:k Stuff
Stuff :: (* -> * -> * -> *) -> Constraint
```

This also explains why you mention that it’s a good pragma to make documentation more explicit.

**Comment by i-am-tom** [comment]
Solved - thanks again for your patience!
