### ISSUE TITLE
Solutions?

### ISSUE THREAD

**Issue by simpadjo** [i-am-tom/haskell-exercises#5]
Thank you so much for the course!
Is there any link to the canonical solutions?

**Comment by i-am-tom** [comment]
It is something I'm working on right now! @ZooeyMiller and @elliotdavies have unknowingly volunteered themselves to help put together the "model answers" along with improving the questions in general :)

**Comment by simpadjo** [comment]
Cool. Should I later submit a feedback which exercise I struggled on most?

**Comment by i-am-tom** [comment]
Yes! I would love any and all feedback :D

**Comment by i-am-tom** [comment]
Posting the work so far and closing this - thanks for bringing it up! https://github.com/i-am-tom/haskell-exercises/tree/answers

**Comment by simpadjo** [comment]
@i-am-tom just in case you missed: I sent you a feedback to tomjharding@live.co.uk

**Comment by i-am-tom** [comment]
Yes! Thank you for your email :) Work has been pretty hectic, so I'll try to get a proper reply to you by the end of the week!

**Comment by i-am-tom** [comment]
Just so you know: I've had to make a surprise house-move, but I definitely haven't forgotten your email!

**Comment by simpadjo** [comment]
I don't ask for a special personal attention:) I just check 'answers' branch from time to time.
